"""Initial migration: Word, Game, Player, Play and helper tables.

Revision ID: 161fba619cd0
Revises: 
Create Date: 2020-12-13 17:57:29.942144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '161fba619cd0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gametype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_type', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gametype')),
    sa.UniqueConstraint('game_type', name=op.f('uq_gametype_game_type'))
    )
    op.create_table('language',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_language')),
    sa.UniqueConstraint('language', name=op.f('uq_language_language'))
    )
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_player')),
    sa.UniqueConstraint('name', name=op.f('uq_player_name'))
    )
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('game_type', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_type'], ['gametype.id'], name=op.f('fk_game_game_type_gametype')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_game'))
    )
    op.create_table('word',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=100), nullable=True),
    sa.Column('times_used', sa.Integer(), nullable=True),
    sa.Column('language', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['language'], ['language.id'], name=op.f('fk_word_language_language')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_word')),
    sa.UniqueConstraint('word', name=op.f('uq_word_word'))
    )
    op.create_table('play',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('word', sa.Integer(), nullable=False),
    sa.Column('game', sa.Integer(), nullable=False),
    sa.Column('player', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game'], ['game.id'], name=op.f('fk_play_game_game')),
    sa.ForeignKeyConstraint(['player'], ['player.id'], name=op.f('fk_play_player_player')),
    sa.ForeignKeyConstraint(['word'], ['word.id'], name=op.f('fk_play_word_word')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_play'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('play')
    op.drop_table('word')
    op.drop_table('game')
    op.drop_table('player')
    op.drop_table('language')
    op.drop_table('gametype')
    # ### end Alembic commands ###
