"""Initial migration.

Revision ID: 2678b899aee4
Revises:
Create Date: 2021-01-29 09:40:58.285029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2678b899aee4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(name='is_active'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin')),
    sa.UniqueConstraint('admin_name', name=op.f('uq_admin_admin_name')),
    sa.UniqueConstraint('email', name=op.f('uq_admin_email'))
    )
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('gametype', sa.Enum('normal', 'timed', name='gametypeenum'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_game'))
    )
    op.create_table('language',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_language')),
    sa.UniqueConstraint('language', name=op.f('uq_language_language'))
    )
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_player')),
    sa.UniqueConstraint('name', name=op.f('uq_player_name'))
    )
    op.create_table('token_blacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('token_type', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('revoked', sa.Boolean(name='is_revoked'), nullable=False),
    sa.Column('expires', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['admin.id'], name=op.f('fk_token_blacklist_user_id_admin')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_token_blacklist')),
    sa.UniqueConstraint('jti', name=op.f('uq_token_blacklist_jti'))
    )
    op.create_table('word',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=100), nullable=True),
    sa.Column('times_used', sa.Integer(), nullable=True),
    sa.Column('language_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], name=op.f('fk_word_language_id_language')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_word')),
    sa.UniqueConstraint('word', name=op.f('uq_word_word'))
    )
    op.create_table('play',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], name=op.f('fk_play_game_id_game')),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], name=op.f('fk_play_player_id_player')),
    sa.ForeignKeyConstraint(['word_id'], ['word.id'], name=op.f('fk_play_word_id_word')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_play'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('play')
    op.drop_table('word')
    op.drop_table('token_blacklist')
    op.drop_table('player')
    op.drop_table('language')
    op.drop_table('game')
    op.drop_table('admin')
    # ### end Alembic commands ###
