"""Added| Game-Player relationship

Revision ID: 740b5c132f6d
Revises: e683874cab38
Create Date: 2021-02-05 12:44:24.120799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '740b5c132f6d'
down_revision = 'e683874cab38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_players',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], name=op.f('fk_game_players_game_id_game')),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], name=op.f('fk_game_players_player_id_player'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_players')
    # ### end Alembic commands ###
