"""Added avatar column

Revision ID: 805cf14e0c96
Revises: 740b5c132f6d
Create Date: 2021-02-12 19:05:16.442538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '805cf14e0c96'
down_revision = '740b5c132f6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('avatar', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'avatar')
    # ### end Alembic commands ###
