"""Changed Language model

Revision ID: dffa6c03ee4e
Revises: 2678b899aee4
Create Date: 2021-01-30 12:04:11.592361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dffa6c03ee4e'
down_revision = '2678b899aee4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('language') as batch_op:
        batch_op.drop_constraint('uq_language_language', type_='unique')
        batch_op.drop_column('language')
        batch_op.add_column(sa.Column('name', sa.String(length=60), nullable=True))
        batch_op.create_unique_constraint(op.f('uq_language_name'), ['name'])
    op.add_column(sa.Column('code', sa.String(length=2), nullable=True))
    op.create_unique_constraint(op.f('uq_language_code'), ['code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('language', sa.Column('language', sa.VARCHAR(length=60), nullable=True))
    op.create_unique_constraint('uq_language_language', 'language', ['language'])
    op.drop_constraint(op.f('uq_language_name'), 'language', type_='unique')
    op.drop_constraint(op.f('uq_language_code'), 'language', type_='unique')
    op.drop_column('language', 'name')
    op.drop_column('language', 'code')
    # ### end Alembic commands ###
